# default configuration
baseURL = "http://sharathmacherla/portfolio/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Myportfolio"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#41228e"
# contact info
phone = "+91 8341280615"
email = "sharathm451@gmail.com"
address = "15-218, Narsampet, Telangana, India"
# meta description
author = "Sharath Macherla"
description = "Hi, you can find little about me here"
# google analytics
google_analytics_id = "" # Your ID
# baidu site verification
baidu_site_verification = "" #Your verification code
# baidu analytics
baidu_analytics_id = "" #Your ID
# copyright
copyright = "Copyright &copy; 2021 a Theme by [Gethugothemes](https://gethugothemes.com)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact


# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-github"
URL = "https://github.com/sharathm451/Projects-AI-ML"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/python_nightcoder/"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/in/macherla-sharath-712b95187/"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/sharathm451/"